# Generated by Django 3.1.3 on 2020-12-02 17:20

from django.conf import settings
from django.db import migrations, models
import quotes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.SET(quotes.models.get_sentinel_user), to='auth.user'),
            preserve_default=False,
        ),
    ]
